"""init schema

Revision ID: 37489cd1ece9
Revises: 
Create Date: 2026-04-29 13:07:04.854641

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37489cd1ece9'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_offices',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('business_number', sa.String(length=20), nullable=True),
    sa.Column('representative', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('tax_office_id', sa.String(length=32), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('business_number', sa.String(length=20), nullable=True),
    sa.Column('representative', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=40), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('kakao_channel_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tax_office_id'], ['tax_offices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clients_tax_office', 'clients', ['tax_office_id'], unique=False)
    op.create_table('monthly_filings',
    sa.Column('tax_office_id', sa.String(length=32), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'COLLECTING', 'REVIEWING', 'APPROVED', 'EXCEL_GENERATED', 'FILED', 'COMPLETED', name='monthlyfilingstatus', native_enum=False, length=20), nullable=False),
    sa.Column('total_clients', sa.Integer(), nullable=False),
    sa.Column('total_entries', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tax_office_id'], ['tax_offices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tax_office_id', 'period', name='uq_filing_office_period')
    )
    op.create_index('ix_filings_office', 'monthly_filings', ['tax_office_id'], unique=False)
    op.create_table('users',
    sa.Column('tax_office_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tax_office_id'], ['tax_offices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_email_unique', 'users', ['email'], unique=True)
    op.create_table('collection_sessions',
    sa.Column('monthly_filing_id', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'RECEIVED', 'NEEDS_REVIEW', 'APPROVED', name='collectionsessionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('request_token', sa.String(length=64), nullable=False),
    sa.Column('request_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['monthly_filing_id'], ['monthly_filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_collection_client', 'collection_sessions', ['client_id'], unique=False)
    op.create_index('ix_collection_filing', 'collection_sessions', ['monthly_filing_id'], unique=False)
    op.create_table('employees',
    sa.Column('client_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rrn_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('rrn_last4', sa.String(length=4), nullable=True),
    sa.Column('employee_code', sa.String(length=40), nullable=True),
    sa.Column('wehago_employee_id', sa.String(length=40), nullable=True),
    sa.Column('hired_at', sa.Date(), nullable=True),
    sa.Column('resigned_at', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'RESIGNED', 'PENDING', name='employmentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_employees_client', 'employees', ['client_id'], unique=False)
    op.create_index('ix_employees_client_name', 'employees', ['client_id', 'name'], unique=False)
    op.create_table('collection_events',
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('file_ref', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['collection_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_session', 'collection_events', ['session_id'], unique=False)
    op.create_table('payroll_entries',
    sa.Column('monthly_filing_id', sa.String(length=32), nullable=False),
    sa.Column('collection_session_id', sa.String(length=32), nullable=False),
    sa.Column('client_id', sa.String(length=32), nullable=False),
    sa.Column('employee_id', sa.String(length=32), nullable=True),
    sa.Column('raw_name', sa.String(length=100), nullable=False),
    sa.Column('income_type', sa.Enum('WAGE', 'BUSINESS', 'OTHER', 'DAILY', 'RETIREMENT', name='incometype', native_enum=False, length=20), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('non_taxable', sa.Integer(), nullable=False),
    sa.Column('taxable', sa.Integer(), nullable=False),
    sa.Column('income_tax', sa.Integer(), nullable=False),
    sa.Column('local_tax', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('dependents', sa.Integer(), nullable=False),
    sa.Column('match_status', sa.Enum('MATCHED', 'NEW_HIRE_SUSPECTED', 'RESIGNATION_SUSPECTED', 'AMBIGUOUS', name='matchstatus', native_enum=False, length=30), nullable=False),
    sa.Column('prev_amount', sa.Integer(), nullable=True),
    sa.Column('anomaly_notes', sa.JSON(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['collection_session_id'], ['collection_sessions.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['monthly_filing_id'], ['monthly_filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payroll_employee', 'payroll_entries', ['employee_id'], unique=False)
    op.create_index('ix_payroll_filing', 'payroll_entries', ['monthly_filing_id'], unique=False)
    op.create_index('ix_payroll_session', 'payroll_entries', ['collection_session_id'], unique=False)
    op.create_table('secure_tokens',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=32), nullable=False),
    sa.Column('collection_session_id', sa.String(length=32), nullable=True),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['collection_session_id'], ['collection_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_secure_tokens_token', 'secure_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_secure_tokens_token', table_name='secure_tokens')
    op.drop_table('secure_tokens')
    op.drop_index('ix_payroll_session', table_name='payroll_entries')
    op.drop_index('ix_payroll_filing', table_name='payroll_entries')
    op.drop_index('ix_payroll_employee', table_name='payroll_entries')
    op.drop_table('payroll_entries')
    op.drop_index('ix_event_session', table_name='collection_events')
    op.drop_table('collection_events')
    op.drop_index('ix_employees_client_name', table_name='employees')
    op.drop_index('ix_employees_client', table_name='employees')
    op.drop_table('employees')
    op.drop_index('ix_collection_filing', table_name='collection_sessions')
    op.drop_index('ix_collection_client', table_name='collection_sessions')
    op.drop_table('collection_sessions')
    op.drop_index('ix_users_email_unique', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_filings_office', table_name='monthly_filings')
    op.drop_table('monthly_filings')
    op.drop_index('ix_clients_tax_office', table_name='clients')
    op.drop_table('clients')
    op.drop_table('tax_offices')
    # ### end Alembic commands ###
