"""add_business_type_codes_table

Revision ID: 47d127e07957
Revises: 37489cd1ece9
Create Date: 2026-05-11 16:09:37.749170

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47d127e07957'
down_revision: str | None = '37489cd1ece9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_type_codes',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('tax_rate_percent', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.add_column('clients', sa.Column('is_corporation', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('clients', sa.Column('file_password', sa.LargeBinary(), nullable=True))
    op.add_column('clients', sa.Column('invite_sent', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('employees', sa.Column('business_type_code', sa.String(length=10), nullable=True))
    op.add_column('payroll_entries', sa.Column('a_code', sa.String(length=5), nullable=True))
    op.add_column('payroll_entries', sa.Column('business_type_code', sa.String(length=10), nullable=True))
    op.add_column('payroll_entries', sa.Column('salary_amount', sa.Integer(), nullable=True))
    op.add_column('payroll_entries', sa.Column('bonus_amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payroll_entries', 'bonus_amount')
    op.drop_column('payroll_entries', 'salary_amount')
    op.drop_column('payroll_entries', 'business_type_code')
    op.drop_column('payroll_entries', 'a_code')
    op.drop_column('employees', 'business_type_code')
    op.drop_column('clients', 'invite_sent')
    op.drop_column('clients', 'file_password')
    op.drop_column('clients', 'is_corporation')
    op.drop_table('business_type_codes')
    # ### end Alembic commands ###
